[database]  #适用于被 viper解析的配置项
    pkg = "./xml"
    driverName = "mysql"
    dsn = "root:root@(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local"
    maxOpenConn = 5 #默认为5
    maxIdleConn = 10 #默认为10
    connMaxLifetime = 5 #默认5分钟
    connMaxIdleTime = 5 #默认5分钟
    printSql = true
    printXml = false
    printWarn = false
    txEnable = false
    logFile = "./log" #""

[database2] #适用于被 viper解析的配置项
    pkg = "./xml"
    driverName = "mysql"
    dsn = "root:root@(127.0.0.1:3306)/test1?charset=utf8&parseTime=True&loc=Local"
    maxOpenConn = 5 #默认为5
    maxIdleConn = 10 #默认为10
    connMaxLifetime = 5 #默认5分钟
    connMaxIdleTime = 5 #默认5分钟
    printSql = false
    printXml = false
    printWarn = false
    txEnable = false
    logFile = "./log"

#[database]#适用于被yaml,toml解析的配置项
#    pkg = "./"
#    driver_name = "mysql"
#    dsn = "root:root@(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local"
#    max_open_conn = 5 #默认为5
#    max_idle_conn = 10 #默认为10
#    conn_max_life_time = 5 #默认5分钟
#    conn_max_idle_time = 5 #默认5分钟
#    print_sql = true
#    print_xml = true
#    print_warn = true
#    tx_enable = true
#    log_file  = ""
#    log_prefix = ""

